### ISSUE TITLE
Restaurante

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/restaurante#2]
@emmanuelmarcosdeoliveira 

Dar  o Inicio ao projeto Restaurante 

- [x] Start

![Image](https://github.com/emmanuelmarcosdeoliveira/restaurante/assets/122749906/d95ad4aa-2fcd-4b5a-b0fb-2bc873aadb78)

**Comment by emmanuelmarcosdeoliveira** [comment]
Iniciado.
@oliveira-emmanuel
